export enum GameEvent {
    GAMESTATE_CHANGED = 'game-state-change',
    START_TIMER = 'start-timer',
    TIME_UP = 'time-up',
    CHIP_ENTRY_READY = 'chip-entry-ready',
    CHIP_SELECTED = 'chip-selected',
    ADD_CHIP_UI = 'add-chip-ui',
    UPDATE_BET_VALUE = 'add-bet-value',
    DECK_LOADED = 'deck-loaded',
    DEAL_CARD = 'deal-card',
    BET_PLACED = "bet-placed",
    ANIMATION_FINISHED = 'animation-finished',
    OFFER_INSURANCE = 'offer-insurance',
    ACCEPT_INSURANCE = 'accept-insurance',
    SPLIT_HAND = 'split-hand',
    CHANGE_HAND = 'change-hand',
    DEALER_TURN_END = 'dealer-turn-end',
    GAME_STARTED = 'game-started',
    GAME_ENDED = 'game-ended',
    PLAYER_MONEY_CHANGED = 'money-changed',
    PAYOUT = 'payout',
    GAME_RESET = 'game-reset',
    LOCK_INPUT = 'lock-input',
    UNLOCK_INPUT = 'unlock-input',
    PLAY_SFX = 'play-sfx',
    SAVE_GAME_LOG = 'save-game-log'
}